In [1]:
import numpy as np

## Problem-1

In [2]:
def matrix_multiplication(matrix1, matrix2):
    try:
        result = np.dot(matrix1, matrix2)
        return result
    except ValueError as e:
        print(f"Error: {e}")
        return None

In [3]:
K, N, A = 2, 3, 4  
matrix_KN = np.random.rand(K, N)
matrix_NA = np.random.rand(N, A)

result_matrix = matrix_multiplication(matrix_KN, matrix_NA)

if result_matrix is not None:
    print(f"Matrix 1 ({K}x{N}):")
    print(matrix_KN)
    print(f"\nMatrix 2 ({N}x{A}):")
    print(matrix_NA)
    print(f"\nResult Matrix ({K}x{A}):")
    print(result_matrix)

Matrix 1 (2x3):
[[0.04405346 0.91097635 0.76453476]
 [0.65070637 0.60063575 0.27447766]]

Matrix 2 (3x4):
[[0.59280225 0.80622731 0.88754934 0.36154647]
 [0.33602497 0.85528236 0.97474751 0.20423513]
 [0.54542577 0.41264481 0.75774035 0.48831893]]

Result Matrix (2x4):
[[0.74922275 1.1301404  1.50639039 0.57531754]
 [0.737276   1.15159218 1.37098501 0.49196414]]


## Problem-2

In [5]:
def check_element_composition(arr):
    composed_elements = np.char.isalnum(arr)

    all_elements_composed = np.all(composed_elements)

    return all_elements_composed

example_array = np.array(['Abc123', 'Def456', 'Ghi789', 'Invalid@'])

result = check_element_composition(example_array)

if result:
    print("All elements are composed of digits, lowercase letters, and uppercase letters only.")
else:
    print("Not all elements satisfy the condition.")

Not all elements satisfy the condition.


## Problem-3

In [6]:
X, Y = map(int, input("Enter two space-separated positive integers X and Y: ").split())

lst1 = list(range(1, 16*X, X))
lst2 = list(range(1, 16*Y, Y))

np1 = np.array(lst1)
np2 = np.array(lst2)

np1 = np1.reshape((4, 4))
np2 = np2.reshape((4, 4))

np3 = np1 - np2

print(f"[{np3.flatten()[0]} {np3.flatten()[1]} {np3.flatten()[2]} {np3.flatten()[3]} "
      f"{np3.flatten()[4]} {np3.flatten()[5]} {np3.flatten()[6]} {np3.flatten()[7]} "
      f"{np3.flatten()[8]} {np3.flatten()[9]} {np3.flatten()[10]} {np3.flatten()[11]} "
      f"{np3.flatten()[12]} {np3.flatten()[13]} {np3.flatten()[14]} {np3.flatten()[15]}]")


Enter two space-separated positive integers X and Y: 5  6
[0 -1 -2 -3 -4 -5 -6 -7 -8 -9 -10 -11 -12 -13 -14 -15]


## Problem-4

In [8]:
def print_elementwise_difference(matrix_P, matrix_Q):
    try:
        result_matrix = matrix_P - matrix_Q

        print("Element-wise difference (P - Q):")
        print(result_matrix)

    except ValueError as e:
        print(f"Error: {e}")

matrix_P = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix_Q = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

if matrix_P.shape == matrix_Q.shape == (3, 3):
    print_elementwise_difference(matrix_P, matrix_Q)
else:
    print("Error: Matrices P and Q must have the same shape [3x3].")

Element-wise difference (P - Q):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


# END